package test;

import static org.junit.Assert.*;

import org.junit.Test;

import main.Multiply;
import main.Sum;

public class TestMultiply {

	@Test
	public void testMultiply() {
		assertEquals(4, Multiply.multiply(2, 2));
	}
	
	@Test
	public void testMultiply2() {
		assertEquals(2, Multiply.multiply(1,1, 2));
	}
	
	@Test
	public void testMultiplyNumWithZero() {
		assertEquals(0, Multiply.multiply(3, 0));
		assertEquals(0, Multiply.multiply(0, 3));
	}
	
	@Test
	public void testMultiplyNumNeg() {
		assertEquals(6, Multiply.multiply(-3, -3));
		assertEquals(2, Sum.sum(5, -3));
	}
	
	@Test(expected=AssertionError.class)
	public void testSum2Fail() {
		assertEquals(5, Sum.sum(2, 2));
	}
	
	@Test(expected=AssertionError.class)
	public void testSum3Fail() {
		assertEquals(3, Sum.sum(1,1, 2));
	}
	
	@Test(expected=AssertionError.class)
	public void testSumNumWithZeroFail() {
		assertEquals(3, Sum.sum(3, 0));
		assertEquals(0, Sum.sum(0, 3));
	}
	
	@Test(expected=AssertionError.class)
	public void testSumNumNegFail() {
		assertEquals(6, Sum.sum(-3, -3));
		assertEquals(-2, Sum.sum(5, -3));
	}

}
